version: '3'
services:
  hello-container:
    image: 'gentux/alpine-bash:laurencoker512'
    volumes: 
      - ${WEB_APP_PATH}:${WEB_DESTINATION_PATH}
    command: sh ./home/welcome-compose.sh
  data-container:
    image: 'alpine:latest'
    volumes:
      - ${WEB_APP_PATH}:${WEB_DESTINATION_PATH}
