version: '3'
services:
  hello-container:
    image: 'nginx:1-alpine'
    depends_on:
      - data-container
    volumes: 
      - "scriptsdir:/home/scripts"
  data-container:
    build:
      context: .
    volumes:
      - "scriptsdir:/home/scripts"

volumes:
  scriptsdir: