version: '3.7'
services:
  hello-container:
    image: 'gentux/alpine-bash:laurencoker512'
    volumes: 
      - "./scripts:/home/scripts"
    command: sh /home/scripts/welcome-compose.sh
  data-container:
    image: 'gentux/alpine-data:laurencoker512'
    volumes:
      - "./scripts:/home/scripts"

volumes:
  scriptsdir:
